Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
show(
    plot_poincare(peaks, input_type='peaks', backend='bokeh', figsize=400)
)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_33032/2296240526.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m show(
[1;32m----> 2[1;33m     [0mplot_poincare[0m[1;33m([0m[0mpeaks[0m[1;33m,[0m [0minput_type[0m[1;33m=[0m[1;34m'peaks'[0m[1;33m,[0m [0mbackend[0m[1;33m=[0m[1;34m'bokeh'[0m[1;33m,[0m [0mfigsize[0m[1;33m=[0m[1;36m400[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m )

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\systole\plots\plot_poincare.py[0m in [0;36mplot_poincare[1;34m(rr, input_type, figsize, backend, ax)[0m
[0;32m    101[0m [1;33m[0m[0m
[0;32m    102[0m     plotting_function = get_plotting_function(
[1;32m--> 103[1;33m         [1;34m"plot_poincare"[0m[1;33m,[0m [1;34m"plot_poincare"[0m[1;33m,[0m [0mbackend[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    104[0m     )
[0;32m    105[0m     [0mplot[0m [1;33m=[0m [0mplotting_function[0m[1;33m([0m[1;33m**[0m[0mplot_poincare_args[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\systole\plots\utils.py[0m in [0;36mget_plotting_function[1;34m(plot_name, plot_module, backend)[0m
[0;32m     44[0m     module = importlib.import_module(
[0;32m     45[0m         "systole.plots.backends.{backend}.{plot_module}".format(
[1;32m---> 46[1;33m             [0mbackend[0m[1;33m=[0m[0mbackend[0m[1;33m,[0m [0mplot_module[0m[1;33m=[0m[0mplot_module[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     47[0m         )
[0;32m     48[0m     )

[1;32mC:\ProgramData\Anaconda3\lib\importlib\__init__.py[0m in [0;36mimport_module[1;34m(name, package)[0m
[0;32m    125[0m                 [1;32mbreak[0m[1;33m[0m[1;33m[0m[0m
[0;32m    126[0m             [0mlevel[0m [1;33m+=[0m [1;36m1[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 127[1;33m     [1;32mreturn[0m [0m_bootstrap[0m[1;33m.[0m[0m_gcd_import[0m[1;33m([0m[0mname[0m[1;33m[[0m[0mlevel[0m[1;33m:[0m[1;33m][0m[1;33m,[0m [0mpackage[0m[1;33m,[0m [0mlevel[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    128[0m [1;33m[0m[0m
[0;32m    129[0m [1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py[0m in [0;36m_gcd_import[1;34m(name, package, level)[0m

[1;32mC:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py[0m in [0;36m_find_and_load[1;34m(name, import_)[0m

[1;32mC:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py[0m in [0;36m_find_and_load_unlocked[1;34m(name, import_)[0m

[1;32mC:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py[0m in [0;36m_load_unlocked[1;34m(spec)[0m

[1;32mC:\ProgramData\Anaconda3\lib\importlib\_bootstrap_external.py[0m in [0;36mexec_module[1;34m(self, module)[0m

[1;32mC:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py[0m in [0;36m_call_with_frames_removed[1;34m(f, *args, **kwds)[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\systole\plots\backends\bokeh\plot_poincare.py[0m in [0;36m<module>[1;34m[0m
[0;32m      8[0m [1;32mfrom[0m [0mbokeh[0m[1;33m.[0m[0mplotting[0m[1;33m.[0m[0mfigure[0m [1;32mimport[0m [0mFigure[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m [1;33m[0m[0m
[1;32m---> 10[1;33m [1;32mfrom[0m [0msystole[0m[1;33m.[0m[0mhrv[0m [1;32mimport[0m [0mnonlinear[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     11[0m [1;33m[0m[0m
[0;32m     12[0m [1;33m[0m[0m

[1;31mImportError[0m: cannot import name 'nonlinear' from 'systole.hrv' (C:\ProgramData\Anaconda3\lib\site-packages\systole\hrv.py)
ImportError: cannot import name 'nonlinear' from 'systole.hrv' (C:\ProgramData\Anaconda3\lib\site-packages\systole\hrv.py)

